version: "3.8"
services:

  couchbase-server:
    build: ./couchbase-server
    ports:
     - 8091-8096:8091-8096
     - 11210:11210
    environment:  
      - CLUSTER_NAME=couchbase-demo
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=P@$$w0rd12
      - COUCHBASE_BUCKET=projects
      - COUCHBASE_BUCKET_RAMSIZE=512
      - COUCHBASE_RBAC_USERNAME=admin
      - COUCHBASE_RBAC_PASSWORD=P@$$w0rd
      - COUCHBASE_RBAC_NAME=admin
      - COUCHBASE_RAM_SIZE=2048
      - COUCHBASE_EVENTING_RAM_SIZE=512
      - COUCHBASE_INDEX_RAM_SIZE=512
    hostname: couchbase-server
    container_name: couchbase-server
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true      
    networks:
      - workshop
    entrypoint: [""]
    command: sh -c "/opt/couchbase/init/init-cbserver.sh"

  sync-gateway:
    build: ./sync-gateway
    ports:
      - 4984-4986:4984-4986
    hostname: sync-gateway
    container_name: sync-gateway
    depends_on:
      - couchbase-server
    working_dir: /docker-syncgateway
    stdin_open: true
    tty: true      
    networks:
      - workshop
    entrypoint: [""]
    command: |
      sh -c '
      # Wait for Couchbase to be ready
      sleep 30
    
      # Track if setup is complete
      FILE=/setupComplete.txt

      if ! [ -f "$FILE" ]; then
        # Create file to track setup completion
        touch $FILE
      else 
        sleep 10
      fi
    
      # Start Sync Gateway with config
      /entrypoint.sh /etc/sync_gateway/config.json &

      # Keep container running
      tail -f /dev/null
      '


networks:
  workshop:
    driver: bridge
